# Generated by Django 2.2.16 on 2022-01-26 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20220126_1855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique follow',
        ),
        migrations.AlterModelTable(
            name='follow',
            table=None,
        ),
    ]
